name: karmastep_eden
description: A global green conquest game.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.3
  google_maps_flutter: ^2.5.0
  sensors_plus: ^4.0.2
  geolocator: ^10.1.0
  provider: ^6.0.5
  percent_indicator: ^4.2.3
  pedometer: ^4.0.2

flutter:
  uses-material-design: true