name: eden
description: A global win-win impact tracking app.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  pedometer: ^4.0.1
  google_maps_flutter: ^2.5.3
  provider: ^6.1.1
  percent_indicator: ^4.2.3

flutter:
  uses-material-design: true