// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXJYaBaqKU3gpYXgA7Iv6C4COSTTAF4Do',
    appId: '1:550101334827:web:ea3e827e9b3b165b3ea36e',
    messagingSenderId: '550101334827',
    projectId: 'karmastep-app',
    authDomain: 'karmastep-app.firebaseapp.com',
    storageBucket: 'karmastep-app.firebasestorage.app',
    measurementId: 'G-6PMXPK6ZCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF3_smxLbeY1Ji-4rGihbhtFEKn28Po7E',
    appId: '1:550101334827:android:61211dbec1adc57e3ea36e',
    messagingSenderId: '550101334827',
    projectId: 'karmastep-app',
    storageBucket: 'karmastep-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ2LIkiRLrcR2Sg4gsmcSYXywiOZXrByM',
    appId: '1:550101334827:ios:241ab5eac0d8d4503ea36e',
    messagingSenderId: '550101334827',
    projectId: 'karmastep-app',
    storageBucket: 'karmastep-app.firebasestorage.app',
    iosBundleId: 'com.example.eden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ2LIkiRLrcR2Sg4gsmcSYXywiOZXrByM',
    appId: '1:550101334827:ios:241ab5eac0d8d4503ea36e',
    messagingSenderId: '550101334827',
    projectId: 'karmastep-app',
    storageBucket: 'karmastep-app.firebasestorage.app',
    iosBundleId: 'com.example.eden',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXJYaBaqKU3gpYXgA7Iv6C4COSTTAF4Do',
    appId: '1:550101334827:web:8aae7f06ebdb3f513ea36e',
    messagingSenderId: '550101334827',
    projectId: 'karmastep-app',
    authDomain: 'karmastep-app.firebaseapp.com',
    storageBucket: 'karmastep-app.firebasestorage.app',
    measurementId: 'G-H1WCTWLZX5',
  );
}
